:sparkles: Add pymongo[srv] to container
ubidots/docker-ubifunction-python3.6Action pull request #24
Opened 2021-03-29 21:07 UTC by Benzer1406

2021-03-29 21:12 UTC, woakas requested changes

2021-03-29 21:12 UTC, woakas commented on README.md
> +gevent == 21.1.1
Please remove the whitespaces for the PR

2021-03-29 21:12 UTC, woakas commented on requirements.txt
> +pymongo[srv]==3.11.3
You should add pymongo and pymongo[srv]

2021-04-06 12:51 UTC, jotathebest approved these changes

2021-04-06 12:57 UTC, woakas approved these changes

2021-04-07 15:44 UTC, merged